/*** Generated by streamline 0.1.36-stack - DO NOT EDIT ***/
"use strict";
var __global = typeof global !== 'undefined' ? global : window;var __srcName='./lib/streams/client/streams_.js';function __Frame(line, name){ this.line = line; this.name = name; this.prev = __global.__frame; __global.__frame = this; };__Frame.prototype.file = __srcName;__Frame.prototype.err = function(_, e){e.__frame = e.__frame || this.prev;__global.__frame = this;__propagate(_, e);};
function __cb(_, frame, offset, col, fn){ var ctx = __global.__context; frame.offset = offset; frame.col = col; return function ___(err, result){ __global.__frame = frame; __global.__context = ctx; if (err) { err.__frame = err.__frame || frame; return _(err); } try { return fn(null, result); } catch (ex) { ex.__frame = ex.__frame || frame; return __propagate(_, ex); } } }
function __future(fn, args, i){ var done, err, result; var cb = function(e, r){ done = true; err = e, result = r; }; args = Array.prototype.slice.call(args); args[i] = function ___(e, r){ cb(e, r); }; fn.apply(this, args); return function ___(_){ if (done) _.call(this, err, result); else cb = _.bind(this); } .bind(this); }
function DataBuffer(options) {
  var _chunks = [];
  this.read = function read__1(_, len) {
    if (!_) {
      return __future(read__1, arguments, 0);
    }
  ;
    var __frame = new __Frame(21, "read__1");
    try {
      var chunks, total, chunk;
      if ((len < 0)) {
        len = Infinity;
      }
    ;
      if ((len == 0)) {
        return _(null, "");
      }
    ;
      chunks = [];
      total = 0;
      while ((total < len)) {
        chunk = _chunks.splice(0, 1)[0];
        if (!chunk) {
          return _(null, ((chunks.length == 0) ? null : chunks.join("")));
        }
      ;
        if (((total + chunk.length) <= len)) {
          chunks.push(chunk);
          total += chunk.length;
        }
         else {
          chunks.push(chunk.substring(0, (len - total)));
          _chunks.splice(0, 0, chunk.substring((len - total)));
          total = len;
        }
      ;
      };
      return _(null, chunks.join(""));
    } catch (e) {
      __frame.err(_, e);
    };
  };
  this.readAll = function readAll__2(_) {
    if (!_) {
      return __future.call(this, readAll__2, arguments, 0);
    }
  ;
    var __frame = new __Frame(45, "readAll__2");
    try {
      var __this = this;
      return __this.read(__cb(_, __frame, 1, 9, _), -1);
    } catch (e) {
      __frame.err(_, e);
    };
  };
  this.unread = function(chunk) {
    _chunks.splice(0, 0, chunk);
    return this;
  };
  this.write = function write__3(_, data, enc) {
    if (!_) {
      return __future.call(this, write__3, arguments, 0);
    }
  ;
    var __frame = new __Frame(56, "write__3");
    try {
      var __this = this;
      _chunks.push(data);
      return _(null, __this);
    } catch (e) {
      __frame.err(_, e);
    };
  };
  this.end = function(data, enc) {
    if (data) {
      _chunks.push(data);
    };
    return this;
  };
  this.contents = function() {
    return _chunks.join("");
  };
};
function HttpError(statusCode, message) {
  this.statusCode = statusCode;
  this.message = message;
  this.stack = new Error().stack;
};
function _fixHttpClientOptions(options) {
  if (!options) {
    throw new Error("request error: no options")
  };
  if ((typeof options === "string")) {
    options = {
      url: options
    };
  };
  return options;
};
function HttpClientRequest(options) {
  options = _fixHttpClientOptions(options);
  DataBuffer.call(this, options);
  var _xhr;
  this.response = function(callback) {
    if (!callback) {
      return __future.call(this, this.response, arguments, 0)
    };
    $.ajax({
      url: options.url,
      headers: options.headers,
      type: options.method,
      data: this.contents(),
      dataType: "text",
      beforeSend: function(xhr) {
        _xhr = xhr;
      },
      success: function(data, statusText, xhr) {
        callback(null, new HttpClientResponse(data, xhr));
      },
      error: function(xhr, statusText, message) {
        callback(new HttpError(xhr.status, ((statusText + ": ") + message)));
      }
    });
  };
  this.abort = function() {
    (_xhr && _xhr.abort());
    _xhr = null;
  };
};
function HttpClientResponse(data, xhr) {
  DataBuffer.call(this);
  this.end(data);
  this.statusCode = xhr.status;
  this.headers = {
  };
  var self = this;
  xhr.getAllResponseHeaders().replace(/\r\n/g, "\n").split("\n").forEach(function(header) {
    var pair = header.split(":");
    self.headers[pair[0].toLowerCase()] = (pair[1] && pair[1].trim());
  });
};
exports.httpRequest = function(options) {
  return new HttpClientRequest(options);
};