/*** Generated by streamline 0.1.36-stack - DO NOT EDIT ***/
"use strict";
var __global = typeof global !== 'undefined' ? global : window;var __fastCb=true;
function __cb(_, fn){ var ctx = __global.__context; var frame = new Error(); frame.__prev = __global.__frame; return function ___(err, result){ __global.__frame = frame; __global.__context = ctx; if (err) { err.__prev = err.__prev || frame; return _(err); } frame.__valid = true; if (__fastCb) return fn(null, result); try { return fn(null, result); } catch (ex) { ex.__prev = ex.__prev || frame; return __propagate(_, ex); } } }
function __future(fn, args, i){ var done, err, result; var cb = function(e, r){ done = true; err = e, result = r; }; args = Array.prototype.slice.call(args); args[i] = function ___(e, r){ cb(e, r); }; fn.apply(this, args); return function ___(_){ if (done) _.call(this, err, result); else cb = _.bind(this); } .bind(this); }
var streams = require("./streams");
exports.send = function Object$send(_, url, obj) {
  if (!_) {
    return __future(Object$send, arguments, 0);
  }
;
  var json, result;
  json = ((obj && (typeof obj !== "string")) ? JSON.stringify(obj) : obj);
  return streams.httpRequest({
    url: url,
    method: (json ? "POST" : "GET"),
    headers: {
      "content-type": "application/json"
    }
  }).end(json, "utf8").response(__cb(_, function ___(__0, __1) {
    return __1.readAll(__cb(_, function ___(__0, __2) {
      result = __2;
      return _(null, JSON.parse(result));
    }));
  }));
};