/*** Generated by streamline 0.1.23 - DO NOT EDIT ***/

var __global = typeof global !== 'undefined' ? global : window;
function __cb(_, fn) { var ctx = __global.__context; return function(err, result) { __global.__context = ctx; if (err) return _(err); try { return fn(null, result); } catch (ex) { return __propagate(_, ex); } } }
function __propagate(_, err) { try { _(err); } catch (ex) { __trap(ex); } }
function __trap(err) { if (err) { if (__global.__context && __global.__context.errorHandler) __global.__context.errorHandler(err); else console.error("UNCAUGHT EXCEPTION: " + err.message + "\n" + err.stack); } }
            (function(_wait) {
              var __then = (_wait = (_wait || __trap));
/*    16 */   return setTimeout(__cb(_wait, function() {
/*    24 */     console.log("the next error should be reported from line 25!");
/*    25 */     undefined.true;
                return __then();
/*    16 */   }), 1000);
            })();
