/*** Generated by streamline 0.1.44 - DO NOT EDIT ***/ var __g=typeof global!=='undefined'?global:window;__g=(__g.__streamline||(__g.__streamline={}));__g.setEF=__g.setEF||function(e,f){e.__frame = e.__frame||f};var __srcName='streamline/lib/tools/docTool_.js'; function __func(_, __this, __arguments, fn, index, frame, body){ if (!_) { return __future.call(__this, fn, __arguments, index); } frame.file = __srcName; frame.prev = __g.frame; __g.frame = frame; try { body(); } catch (e) { __g.setEF(e, frame.prev); __propagate(_, e); } finally { __g.frame = frame.prev; } } function __cb(_, frame, offset, col, fn){ frame.offset = offset; frame.col = col; var ctx = __g.context; return function ___(err, result){ var oldFrame = __g.frame; __g.frame = frame; __g.context = ctx; try { if (err) { __g.setEF(err, frame); return _(err); } return fn(null, result); } catch (ex) { __g.setEF(ex, frame); return __propagate(_, ex); } finally { __g.frame = oldFrame; } } } function __future(fn, args, i){ var done, err, result; var cb = function(e, r){ done = true; err = e, result = r; }; args = Array.prototype.slice.call(args); args[i] = function ___(e, r){ cb(e, r); }; fn.apply(this, args); return function ___(_){ if (done) _.call(this, err, result); else cb = _.bind(this); } .bind(this); } function __propagate(_, err){ try { _(err); } catch (ex) { __trap(ex); } } function __trap(err){ if (err) { if (__g.context && __g.context.errorHandler) __g.context.errorHandler(err); else console.error("UNCAUGHT EXCEPTION: " + err.message + "\n" + err.stack); } } (function main(_) { var fs, fsp; var __frame = { name: "main", line: 1 }; return __func(_, this, arguments, main, 0, __frame, function __$main() {
























 fs = require("fs");
 fsp = require("path");



 exports.generate = function exports_generate__1(_, path, options) {

 function _generate(_, path) { var stat, inside, doc, pair, isPackage, files, i; var __frame = { name: "_generate", line: 33 }; return __func(_, this, arguments, _generate, 0, __frame, function __$_generate() {
 return fs.stat(path, __cb(_, __frame, 1, 13, function ___(__0, __1) { stat = __1; return (function __$_generate(__then) {
 if (stat.isFile()) { return (function __$_generate(__then) {
 if ((path.indexOf(".js") == (path.length - 3))) {

 return fs.readFile(path, "utf8", __cb(_, __frame, 5, 14, function ___(__0, __2) {










 doc = __2.split("\n").map(function(line) { var i = line.indexOf(("//" + "/ ")); line = ((i >= 0) ? line.substring((i + 4)) : null); if ((line === "!doc")) { inside = true; } else if ((line === "!nodoc")) { inside = false; } else return ((inside && (line != null)) ? (line + "\n") : null)  ; }).filter(function(line) { return (line != null); }).join("");
 return _(null, (doc || "")); })); } else { __then(); } ; })(function __$_generate() {

 return _(null, ""); }); } else { return (function __$_generate(__then) {
 if (stat.isDirectory()) {
 pair = path.split("/node_modules/");
 isPackage = (pair[1] && (pair[1].indexOf("/") < 0));
 doc = "";
 return fs.readdir(path, __cb(_, __frame, 24, 15, function ___(__0, __3) { files = __3;
 i = 0; var __9 = false; return (function ___(__break) { var __more; var __loop = __cb(_, __frame, 0, 0, function __$_generate() { __more = false; if (__9) { i++; } else { __9 = true; } ; var __8 = (i < files.length); if (__8) {
 return _generate(__cb(_, __frame, 26, 11, function ___(__0, __4) { doc += __4; while (__more) { __loop(); }; __more = true; }), ((path + "/") + files[i])); } else { __break(); } ; }); do { __loop(); } while (__more); __more = true; })(function __$_generate() { return (function __$_generate(__then) {

 if ((isPackage && doc)) {
 return fs.writeFile((path + "/API.md"), doc, "utf8", __cb(_, __frame, 29, 4, function __$_generate() {
 if (options.verbose) {
 console.log((("generated " + path) + "/API.md")); } ;
 doc = ""; __then(); })); } else { __then(); } ; })(function __$_generate() {

 return _(null, doc); }); }); })); } else {

 return _(null, ""); } ; })(__then); } ; })(_); })); }); }; var __frame = { name: "exports_generate__1", line: 31 }; return __func(_, this, arguments, exports_generate__1, 0, __frame, function __$exports_generate__1() { options = (options || { });

 return _generate(__cb(_, __frame, 40, 1, _), path); }); }; return (function __$main(__then) {


 if ((process.argv[1] && (process.argv[1].indexOf("/docTool") >= 0))) {
 return exports.generate(__cb(_, __frame, 74, 1, __then), fsp.join(process.cwd(), (process.argv[2] || ".")), { verbose: true }); } else { __then(); } ; })(_); });}).call(this, __trap);